name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  vs-ponyc-release:
    name: Test against recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-pcre:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug

  vs-ponyc-release-windows:
    name: Test against recent ponyc release on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test with most recent ponyc release
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Force -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-pc-windows-msvc.zip -OutFile C:\corral.zip;
          Expand-Archive -Force -Path C:\corral.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command libs 2>&1;
          .\make.ps1 -Command test 2>&1;
